export const students = [
  {
    id: "1",
    name: "Syed Ali",
    email: "syed.ali@umt.edu.pk",
    grade: "A+",
    major: "Computer Science",
  },
  {
    id: "2",
    name: "Meerab",
    email: "meerab.Ali@umt.edu.pk",
    grade: "A+",
    major: "Biology",
  },
  {
    id: "3",
    name: "Haris Ahmad",
    email: "haris.ahmad@umt.edu.pk",
    grade: "A-",
    major: "Physics",
  },
  {
    id: "4",
    name: "Laiba Imran",
    email: "laiba@umt.edu.pk",
    grade: "A+",
    major: "Biology",
  },
  {
    id: "5",
    name: "Haider Ali",
    email: "haider.ali@umt.edu.pk",
    grade: "B",
    major: "Chemistry",
  },
  {
    id: "6",
    name: "Maheen Akhtar",
    email: "maheen@umt.edu.pk",
    grade: "A-",
    major: "Economics",
  },
  {
    id: "7",
    name: "Ahmad Khan",
    email: "ahmad.khan@umt.edu.pk",
    grade: "B+",
    major: "Business Administration",
  },
  {
    id: "8",
    name: "Sara Malik",
    email: "sara.malik@umt.edu.pk",
    grade: "A",
    major: "English Literature",
  },
  {
    id: "9",
    name: "Bilal Qureshi",
    email: "bilal.qureshi@umt.edu.pk",
    grade: "B",
    major: "Political Science",
  },
  {
    id: "10",
    name: "Ayesha Siddiqui",
    email: "ayesha.siddiqui@umt.edu.pk",
    grade: "A-",
    major: "Psychology",
  },
  {
    id: "11",
    name: "Usman Tariq",
    email: "usman.tariq@umt.edu.pk",
    grade: "B+",
    major: "Sociology",
  },
  {
    id: "12",
    name: "Zainab Raza",
    email: "zainab.raza@umt.edu.pk",
    grade: "A",
    major: "Fine Arts",
  },
  {
    id: "13",
    name: "Hamza Shahid",
    email: "hamza.shahid@umt.edu.pk",
    grade: "B",
    major: "Mechanical Engineering",
  },
  {
    id: "14",
    name: "Fatima Noor",
    email: "fatima.noor@umt.edu.pk",
    grade: "A+",
    major: "Electrical Engineering",
  },
  {
    id: "15",
    name: "Imran Abbas",
    email: "imran.abbas@umt.edu.pk",
    grade: "B-",
    major: "Civil Engineering",
  },
  {
    id: "16",
    name: "Rabia Javed",
    email: "rabia.javed@umt.edu.pk",
    grade: "A",
    major: "Environmental Science",
  },
  {
    id: "17",
    name: "Shahzaib Ali",
    email: "shahzaib.ali@umt.edu.pk",
    grade: "B+",
    major: "Software Engineering",
  },
  {
    id: "18",
    name: "Nida Farooq",
    email: "nida.farooq@umt.edu.pk",
    grade: "A-",
    major: "Statistics",
  },
  {
    id: "19",
    name: "Waleed Anwar",
    email: "waleed.anwar@umt.edu.pk",
    grade: "B",
    major: "Accounting",
  },
  {
    id: "20",
    name: "Hina Aslam",
    email: "hina.aslam@umt.edu.pk",
    grade: "A",
    major: "Finance",
  },
  {
    id: "21",
    name: "Sami Ullah",
    email: "sami.ullah@umt.edu.pk",
    grade: "B+",
    major: "Marketing",
  },
  {
    id: "22",
    name: "Mariam Yousaf",
    email: "mariam.yousaf@umt.edu.pk",
    grade: "A-",
    major: "Human Resource Management",
  },
  {
    id: "23",
    name: "Taha Khalid",
    email: "taha.khalid@umt.edu.pk",
    grade: "B",
    major: "Supply Chain Management",
  },
  {
    id: "24",
    name: "Sadia Munir",
    email: "sadia.munir@umt.edu.pk",
    grade: "A",
    major: "Mass Communication",
  },
  {
    id: "25",
    name: "Adeel Rafiq",
    email: "adeel.rafiq@umt.edu.pk",
    grade: "B+",
    major: "International Relations",
  },
  {
    id: "26",
    name: "Iqra Shah",
    email: "iqra.shah@umt.edu.pk",
    grade: "A-",
    major: "Islamic Studies",
  },
  {
    id: "27",
    name: "Fahad Mirza",
    email: "fahad.mirza@umt.edu.pk",
    grade: "B",
    major: "History",
  },
  {
    id: "28",
    name: "Sundas Rehman",
    email: "sundas.rehman@umt.edu.pk",
    grade: "A",
    major: "Education",
  },
  {
    id: "29",
    name: "Omer Saeed",
    email: "omer.saeed@umt.edu.pk",
    grade: "B+",
    major: "Philosophy",
  },
  {
    id: "30",
    name: "Noman Zafar",
    email: "noman.zafar@umt.edu.pk",
    grade: "A-",
    major: "Linguistics",
  },
]
